services:
  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      MYSQL_DATABASE: taetaeDB
      MYSQL_USER: taetae
      MYSQL_PASSWORD: root1234!!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: