
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taetaeDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: taetae
    password: root1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          use_sql_comments: true

  sql:
    init:
      platform: mysql

logging:
  level:
    root: INFO
    com.example.concert.filter.LogFilter: DEBUG

  redis:
    host: localhost
    port: 6379